### ISSUE TITLE
Can't Upload Binary Files Using 3.0.x (with Ruby 2.1.0 and Rails 4.2.6)

### ISSUE THREAD

**Issue by sae249833** [ibmdb/ruby-ibmdb#59]
I can't upload binary files into a table containing a blob field using IBM_DB 3.0.1, Ruby 2.1.0 and Rails 4.2.6.

I have defined a very simple table and activerecord model, let's call it SimpleModel.  The table contains 4 columns:

sm_id: the auto generated primary key
sm_mime_type: a string 
sm_filename: a string
sm_thefile: a BLOB

In my rails console I try to insert a new row containing a file from the local file system and it errors out with:

ruby-2.1.0/gems/ibm_db-3.0.1/lib/active_record/connection_adapters/ibm_db_adapter.rb:1206: warning: Execute Failed due to: [IBM][CLI Driver] CLI0125E  Function sequence error. SQLSTATE=HY010 SQLCODE=-99999

This used to work as late as ruby 2.1.0 + rails 4.1.9 + ibm_db 2.5.18.

Here are the steps to reproduce it.

> rails c development
2.1.0> sm = SimpleModel.new
2.1.0> sm.mime_type = 'application/excel'
2.1.0> f = File.open(Rails.root.join('tmp','simple-excel-test-file.xlsx'), 'r')
2.1.0> sm.filename = File.basename(f)
2.1.0> sm.thefile = f.read
2.1.0> sm.save

Please note that I can update any of the other fields in the table and I can upload a plain text file to the BLOB column.  However binary files will NOT work.  I've tried different file types PNGs, Excel files, etc... and they all get this exact same error.  Please assist, thanks!

**Comment by sae249833** [comment]
Also I installed ruby 2.1.9 (still using ibm_db 3.0.1 and rails 4.2.6) and tested but it also did not work...this time no error it just hung indefinitely on the "save" call.

**Comment by sae249833** [comment]
Tried ruby 2.2.5 today and I got the same result as 2.1.9 (hangs indefinitely on the "save" call).  Version 3.0.1 of this gem has a clear bug.

**Comment by arvindgu** [comment]
We are working on issue with uploading binary files into a table containing a blob field and update you as soon as we have fix ready for it.

**Comment by arvindgu** [comment]
We have released ibm_db version 3.0.2 to fix this issue. Please try and let me know.

**Comment by sae249833** [comment]
With 3.0.2 I can now insert a binary file into a BLOB field of a **new** row.  However, if I try to update the BLOB field of an existing row it fails to work correctly.  The value placed into the BLOB field is always x'3F' no matter what binary file I try to update the row with.  So there is still an issue.  Here's a sample scenario (very similar to the one above except it executes a "save" before and after the binary file is inserted.

`rails c development
2.1.9> sm = SimpleModel.new
2.1.9> sm.mime_type = 'application/excel'
2.1.9> sm.save
2.1.9>
2.1.9> f = File.open(Rails.root.join('tmp','simple-excel-test-file.xlsx'), 'r')
2.1.9> sm.filename = File.basename(f)
2.1.9> sm.thefile = f.read
2.1.9> sm.save`

**Comment by arvindgu** [comment]
I was able to reproduce it and it is under investigation.

**Comment by sae249833** [comment]
I haven't been able to workaround this issue.  Is there a status on when a fix might be expected?

**Comment by arvindgu** [comment]
We are investing on this, we will be able to provide update by next week.

**Comment by arvindgu** [comment]
We have released ibm_db gem version 3.0.3 fixing this issue. Please test with this.

**Comment by sae249833** [comment]
In 3.0.4 updating the BLOB field of an existing row still fails to work correctly.  The resulting value is always x'3F'.

**Comment by arvindgu** [comment]
In **database.yml** file, please configure **parameterized: true** and try.

**Comment by sae249833** [comment]
Yes, it does work when correctly when I add the **parameterized: true** configuration.  Thank you.

However, I'm troubled because this configuration was taken out of the gem a while ago.  Including it in the database.yml even started causing an error in later versions.  

For example, in 2.5.18 if you include **parameterized: true** you will receive the following error on any "find" or "where" calls: **TypeError: superclass mismatch for class HasOneAssociation**

Why was this configuration added back to the gem?

**Comment by arvindgu** [comment]
The support for parameterized: true is added back in ibm_db gem version 3.0.4  in response to #58 to support prepared queries. 

There were some changes happened in Rails Active Adapter framework that broke the ibm_db gem option (parameterized: true) to support prepared statements. Yes, earlier versions of gem will throw error when parameterized is set to true.  Now we have worked on it and added back in version 3.0.4.
